singleQuote: true
useTabs: false
tabWidth: 2
printWidth: 120
trailingComma: 'es5'
twigPrintWidth: 5000
twigMultiTags: ['with,endwith']
twigAlwaysBreakObjects: false
twigSingleQuote: false
twigFollowOfficialCodingStandards: false # Set to false if you want spacing around filter pipes

# This is key - it will maintain the template tag formatting you prefer
djangoTemplateBracketSpacing: true

overrides:
  - files: '*.{yaml,yml}'
    options:
      parser: 'yaml'
      proseWrap: 'always'
  - files: '*.md'
    options:
      parser: 'markdown'
      proseWrap: 'always'
  - files: 'README'
    options:
      parser: 'markdown'
      proseWrap: 'always'
  - files: '*.html'
    options:
      parser: 'html'
  - files: '*.css'
    options:
      parser: 'css'
