# Generated by Django 5.0 on 2024-01-11 23:59

import budgetapp.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=budgetapp.utils.generate_uuid_hex,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("balance", models.IntegerField(default=0)),
                ("sort_order", models.IntegerField(default=99)),
                ("hidden", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="budgets.budget"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Envelope",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=budgetapp.utils.generate_uuid_hex,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sort_order", models.IntegerField(default=99)),
                ("balance", models.IntegerField(default=0)),
                ("hidden", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="budgets.budget"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envelopes.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvelopeGoal",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=budgetapp.utils.generate_uuid_hex,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("day", models.PositiveIntegerField(blank=True, null=True)),
                ("cadence", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cadence_frequency",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "creation_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("target_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "percentage_completed",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "months_to_budget",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("under_funded", models.PositiveIntegerField(blank=True, null=True)),
                ("overall_funded", models.PositiveIntegerField(blank=True, null=True)),
                ("overall_left", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "envelope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envelopes.envelope",
                    ),
                ),
            ],
        ),
    ]
