# Generated by Django 5.0 on 2024-02-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("envelopes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="envelope",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
