# Generated by Django 4.2.7 on 2023-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("envelopes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="envelope",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
