# Generated by Django 5.2.1 on 2025-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envelopes", "0002_envelope_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="envelope",
            name="monthly_budget_amount",
            field=models.IntegerField(
                default=0, help_text="Planned monthly allocation amount"
            ),
        ),
    ]
