# Generated by Django 4.2.7 on 2023-11-07 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("envelopes", "0002_alter_category_options_envelope_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="envelope",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="envelope",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EnvelopeGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("day", models.PositiveIntegerField(blank=True, null=True)),
                ("cadence", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cadence_frequency",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "creation_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("target_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "percentage_completed",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "months_to_budget",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("under_funded", models.PositiveIntegerField(blank=True, null=True)),
                ("overall_funded", models.PositiveIntegerField(blank=True, null=True)),
                ("overall_left", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "envelope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envelopes.envelope",
                    ),
                ),
            ],
        ),
    ]
