# Generated by Django 5.0.7 on 2024-08-02 15:53

import budgetapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetapp", "0002_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="id",
            field=models.CharField(
                default=budgetapp.utils.generate_uuid_hex,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
