# Generated by Django 4.2.7 on 2023-11-10 05:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("on_budget", models.BooleanField(default=True)),
                ("closed", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
                ("balance", models.IntegerField(default=0)),
                ("cleared_balance", models.PositiveIntegerField(default=0)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="budgets.budget"
                    ),
                ),
            ],
        ),
    ]
