# Generated by Django 5.0.7 on 2025-03-17 19:53

import budgetapp.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_slug_alter_account_unique_together"),
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleFINConnection",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=budgetapp.utils.generate_uuid_hex,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="budgets.budget"
                    ),
                ),
            ],
        ),
    ]
