# Generated by Django 5.0.7 on 2025-03-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_sfin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="cleared_balance",
            field=models.IntegerField(default=0),
        ),
    ]
