# Generated by Django 5.1.7 on 2025-03-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_cleared_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="sfin_last_imported_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
