# Generated by Django 5.0 on 2023-12-14 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("budgets", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("budget", "account", "import_id")},
        ),
    ]
