# Generated by Django 5.0.7 on 2025-03-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sfin_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
