# Generated by Django 5.0.7 on 2025-03-20 19:47

from django.db import migrations, models


def fix_duplicate_sfin_ids(apps, schema_editor):
    """
    Find and fix transactions with duplicate sfin_ids before applying the unique constraint.
    """
    Transaction = apps.get_model("transactions", "Transaction")

    # Get all transactions with non-null sfin_id
    transactions_with_sfin = Transaction.objects.filter(sfin_id__isnull=False)

    # Track seen combinations of (budget_id, account_id, sfin_id)
    seen = {}

    # Find and fix duplicates
    for transaction in transactions_with_sfin:
        key = (transaction.budget_id, transaction.account_id, transaction.sfin_id)

        if key in seen:
            # This is a duplicate - set sfin_id to None to avoid constraint violation
            transaction.sfin_id = None
            transaction.save()
        else:
            seen[key] = transaction.id


def reverse_fix(apps, schema_editor):
    # This operation cannot be reversed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_cleared_balance"),
        ("budgets", "0001_initial"),
        ("transactions", "0002_transaction_pending_transaction_sfin_id"),
    ]

    operations = [
        # First, update the import_id unique constraint
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("budget", "account", "import_id")},
        ),
        # Update the sfin_id field definition
        migrations.AlterField(
            model_name="transaction",
            name="sfin_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SimpleFIN ID"
            ),
        ),
        # Run data migration to fix duplicates before adding the new constraint
        migrations.RunPython(fix_duplicate_sfin_ids, reverse_fix),
        # Finally, add the combined unique constraint
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={
                ("budget", "account", "import_id"),
                ("budget", "account", "sfin_id"),
            },
        ),
    ]
