# Generated by Django 5.1.7 on 2025-03-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="in_inbox",
            field=models.BooleanField(default=True),
        ),
    ]
