# Generated by Django 5.1.7 on 2025-03-24 15:08

import budgetapp.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
        ("transactions", "0004_transaction_in_inbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionMerge",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=budgetapp.utils.generate_uuid_hex,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="budgets.budget"
                    ),
                ),
                (
                    "merged_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resulting_merge",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "source_transactions",
                    models.ManyToManyField(
                        related_name="source_for_merges", to="transactions.transaction"
                    ),
                ),
            ],
        ),
    ]
