# Generated by Django 5.1.7 on 2025-03-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_cleared_balance"),
        ("budgets", "0001_initial"),
        ("envelopes", "0002_envelope_note"),
        ("transactions", "0005_transactionmerge"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("budget", "account", "import_id"),
                name="unique_budget_account_import_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("budget", "account", "sfin_id"),
                name="unique_budget_account_sfin_id",
            ),
        ),
    ]
