# Generated by Django 5.1.7 on 2025-03-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_transaction_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="approved",
        ),
    ]
