# Generated by Django 5.1.7 on 2025-03-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_cleared_balance"),
        ("budgets", "0001_initial"),
        ("envelopes", "0002_envelope_note"),
        ("transactions", "0007_remove_transaction_approved"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["date"], name="transaction_date_ad8c94_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["amount"], name="transaction_amount_7195ec_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["cleared"], name="transaction_cleared_aea048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["in_inbox"], name="transaction_in_inbo_06faaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["pending"], name="transaction_pending_e8fc5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["deleted"], name="transaction_deleted_1f8979_idx"
            ),
        ),
    ]
