# Generated by Django 5.2.1 on 2025-05-27 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_account_sfin_last_imported_on"),
        ("transactions", "0008_transaction_transaction_date_ad8c94_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_transfer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_transactions",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_transfer",
                to="transactions.transaction",
            ),
        ),
    ]
