# Generated by Django 5.0 on 2024-01-11 23:59

import budgetapp.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=budgetapp.utils.generate_uuid_hex,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_format", models.CharField(default="MM/DD/YYYY", max_length=255)),
                ("currency_iso_code", models.CharField(default="USD", max_length=3)),
                (
                    "currency_decimal_digits",
                    models.PositiveSmallIntegerField(default=2),
                ),
                (
                    "currency_decimal_separator",
                    models.CharField(default=".", max_length=1),
                ),
                ("currency_symbol_first", models.BooleanField(default=True)),
                (
                    "currency_group_separator",
                    models.CharField(default=",", max_length=1),
                ),
                ("currency_symbol", models.CharField(default="$", max_length=48)),
                ("currency_display_symbol", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
