# Generated by Django 4.2.7 on 2023-11-10 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_format", models.CharField(default="MM/DD/YYYY", max_length=255)),
                ("currency_iso_code", models.CharField(default="USD", max_length=3)),
                (
                    "currency_decimal_digits",
                    models.PositiveSmallIntegerField(default=2),
                ),
                (
                    "currency_decimal_separator",
                    models.CharField(default=".", max_length=1),
                ),
                ("currency_symbol_first", models.BooleanField(default=True)),
                (
                    "currency_group_separator",
                    models.CharField(default=",", max_length=1),
                ),
                ("currency_symbol", models.CharField(default="$", max_length=48)),
                ("currency_display_symbol", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
