# Generated by Django 4.2.7 on 2023-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="currency_decimal_digits",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency_decimal_separator",
            field=models.CharField(default=".", max_length=1),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency_display_symbol",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency_group_separator",
            field=models.CharField(default=",", max_length=1),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency_iso_code",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency_symbol",
            field=models.CharField(default="$", max_length=48),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency_symbol_first",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="date_format",
            field=models.CharField(default="MM/DD/YYYY", max_length=255),
        ),
    ]
